{% set version = "0.5.9" %}

package:
  name: grcov
  version: {{ version }}

source:
  url: https://github.com/mozilla/grcov/releases/download/v{{ version }}/grcov-linux-x86_64.tar.bz2  # [linux]
  sha256: "2142df24938b6e56b6b84983d5492c53af486535446cacbd26715c9bfa1e89e4"                         # [linux]
  url: https://github.com/mozilla/grcov/releases/download/v{{ version }}/grcov-osx-x86_64.tar.bz2    # [osx]
  sha256: "bf7fc40d11aad717ca65503b216301dd16ddcf78ec3a79e0eea330123e29b17e"                         # [osx]
  url: https://github.com/mozilla/grcov/releases/download/v{{ version }}/grcov-win-x86_64.tar.bz2    # [win]
  sha256: "6200f2130e663eea3f0c9b0dc6430620d145785e1d5f20e79b2caf0375d8f3ce"                         # [win]

build:
  number: 0
  skip: True  # [not x86_64]

requirements:
  build: []
  host: []  # Empty host dependency section

test:
  commands:
    - test -f ${PREFIX}/bin/grcov                          # [unix]
    - if exist %SCRIPTS%\grcov.exe (exit 0) else (exit 1)  # [win]

about:
  home: https://github.com/mozilla/grcov
  license: Mozilla Public 2.0 (MPL 2.0)
  license_family: OTHER
  summary: Rust tool to collect and aggregate code coverage data for multiple source files
  description: |
    grcov collects and aggregates code coverage information for multiple source files.
    This is a project initiated by Mozilla to gather code coverage results on Firefox.

extra:
  recipe-maintainers:
    - zhihao.yuan
